package pasa.cbentley.framework.core.ui.src4.ctx;

import pasa.cbentley.byteobjects.src4.ctx.IEventsBO;
import pasa.cbentley.core.src4.ctx.IEventsCore;
import pasa.cbentley.core.src4.interfaces.IEvents;
import pasa.cbentley.framework.coredraw.src4.ctx.IEventsCoreDraw;

/**
 * <li>{@link IEventsCore}
 * <li>{@link IEventsBO}
 * <li>{@link IEventsCoreDraw}
 * 
 * @author Charles Bentley
 *
 */
public interface IEventsCoreUi extends IEvents {

   public static final int A_SID_COREUI_EVENT_A                  = 15;

   public static final int A_SID_COREUI_EVENT_Z                  = 20;

   public static final int COREUI_NUM_EVENTS                     = 3;

   public static final int PID_00                                = 0;

   /**
    * ID for all CoreUI events
    */
   public static final int PID_00_ANY                            = A_SID_COREUI_EVENT_A + PID_00;

   public static final int PID_00_XX                             = 1;

   public static final int PID_01                                = 1;

   public static final int PID_01_DEVICE                         = A_SID_COREUI_EVENT_A + PID_01;

   public static final int PID_01_DEVICE_00_ANY                  = 0;

   /**
    * Event that Request the current Virtual Keyboard to open.
    * <br>
    * Might be Host
    */
   public static final int PID_01_DEVICE_01_VIRT_KEYB_REQUEST    = 1;

   public static final int PID_01_DEVICE_02_VIRT_KEYB_OFF        = 2;

   public static final int PID_01_DEVICE_03_VIRT_FLASH_LIGHT_ON  = 3;

   public static final int PID_01_DEVICE_04_VIRT_FLASH_LIGHT_OFF = 4;

   /**
    * Event generated by the {@link IAppli} when its user interface detects
    * settings used by the Host have been modified.
    * <br>
    * The host update
    */
   public static final int PID_01_DEVICE_05_UPDATE               = 5;

   public static final int PID_01_XX                             = 6;

   public static final int PID_02                                = 2;

   public static final int PID_02_CANVAS                         = A_SID_COREUI_EVENT_A + PID_02;

   public static final int PID_02_CANVAS_00_ANY                  = 0;

   /**
    * Event generated by appli when the title/icon have changed and should be updated
    * by the host.
    */
   public static final int PID_02_CANVAS_01_TITLE                = 1;

   /**
    * Event generated when a drag and drop occurred on one of the canvas of the UI.
    */
   public static final int PID_02_CANVAS_02_DRAG_DROP            = 2;

   /**
    * Number of events for producer of Canvas events
    */
   public static final int PID_02_XX                             = 3;

}
